// Full-length section + exam assembly. A section is an ordered list of UNITS,
// each generated by one call to the existing generators and rendered by its
// matching runner. Sections are assembled client-side (multiple calls with a
// progress callback) so each call stays within the serverless time budget.

import {
  generatePassage,
  generateQuestions,
  generateReading,
  generateWriting,
} from "./claude.js";
import { SECTION_PLANS, EXAM_SECTIONS } from "./sectionPlans.js";

export { SECTION_PLANS, EXAM_SECTIONS };

function unitLabel(plan, spec, i) {
  if (spec.kind === "mcq") return `${plan.label} — questions ${i + 1}`;
  if (spec.kind === "reading") return `${plan.label} — passage ${i + 1} (${spec.variant})`;
  return `${plan.label} — passage ${i + 1}`;
}

/**
 * Assemble one section's units. `onProgress({ done, total, label })` fires
 * before each unit. Returns an array of { kind, payload, verified }.
 */
export async function assembleSection(planKey, { apiKey, signal, onProgress } = {}) {
  const plan = SECTION_PLANS[planKey];
  if (!plan) throw new Error(`Unknown section: ${planKey}`);
  const units = [];
  const total = plan.units.length;
  const base = { test: plan.test, subject: plan.subject, apiKey, signal };

  for (let i = 0; i < total; i++) {
    const spec = plan.units[i];
    onProgress?.({ done: i, total, label: unitLabel(plan, spec, i) });
    if (spec.kind === "passage") {
      const { passage, verified } = await generatePassage(base);
      units.push({ kind: "passage", payload: passage, verified });
    } else if (spec.kind === "reading") {
      const { reading, verified } = await generateReading({ ...base, variant: spec.variant });
      units.push({ kind: "reading", payload: reading, verified });
    } else if (spec.kind === "writing") {
      const { writing, verified } = await generateWriting(base);
      units.push({ kind: "writing", payload: writing, verified });
    } else {
      const { questions, verified } = await generateQuestions({ ...base, count: spec.count });
      units.push({ kind: "mcq", payload: { questions }, verified });
    }
  }
  onProgress?.({ done: total, total, label: "Finishing up" });
  return units;
}

// Total questions actually generated across a unit list.
export function countQuestions(units) {
  return units.reduce((sum, u) => sum + (u.payload.questions?.length ?? 0), 0);
}
