// Full-length section + exam assembly. A section is an ordered list of UNITS,
// each generated by one call to the existing generators and rendered by its
// matching runner. Sections are assembled client-side (multiple calls with a
// progress callback) so each call stays within the serverless time budget.

import {
  generatePassage,
  generateQuestions,
  generateReading,
  generateWriting,
} from "./claude.js";

// Each plan: which units to generate, the question target, and a default timer
// (minutes) the user can override. Unit kinds map to the four runners.
export const SECTION_PLANS = {
  "ACT-English": {
    test: "ACT",
    subject: "English",
    label: "ACT English",
    target: 50,
    minutes: 35,
    units: [
      { kind: "passage" },
      { kind: "passage" },
      { kind: "passage" },
      { kind: "passage" },
      { kind: "passage" },
    ],
  },
  "ACT-Reading": {
    test: "ACT",
    subject: "Reading",
    label: "ACT Reading",
    target: 36,
    minutes: 40,
    units: [
      { kind: "reading", variant: "single" },
      { kind: "reading", variant: "single" },
      { kind: "reading", variant: "paired" },
      { kind: "reading", variant: "graph" },
    ],
  },
  "ACT-Math": {
    test: "ACT",
    subject: "Math",
    label: "ACT Math",
    target: 45,
    minutes: 50,
    units: [
      { kind: "mcq", count: 12 },
      { kind: "mcq", count: 12 },
      { kind: "mcq", count: 12 },
      { kind: "mcq", count: 9 },
    ],
  },
  "ACT-Science": {
    test: "ACT",
    subject: "Science",
    label: "ACT Science",
    target: 40,
    minutes: 40,
    units: [
      { kind: "mcq", count: 10 },
      { kind: "mcq", count: 10 },
      { kind: "mcq", count: 10 },
      { kind: "mcq", count: 10 },
    ],
  },
  "SAT-English": {
    test: "SAT",
    subject: "English",
    label: "SAT Reading & Writing",
    target: 27,
    minutes: 32,
    units: [{ kind: "writing" }, { kind: "writing" }, { kind: "writing" }],
  },
  "SAT-Math": {
    test: "SAT",
    subject: "Math",
    label: "SAT Math",
    target: 22,
    minutes: 35,
    units: [
      { kind: "mcq", count: 11 },
      { kind: "mcq", count: 11 },
    ],
  },
};

// Ordered list of section keys for the full-exam mode, per test.
export const EXAM_SECTIONS = {
  ACT: ["ACT-English", "ACT-Math", "ACT-Reading", "ACT-Science"],
  SAT: ["SAT-English", "SAT-Math"],
};

function unitLabel(plan, spec, i) {
  if (spec.kind === "mcq") return `${plan.label} — questions ${i + 1}`;
  if (spec.kind === "reading") return `${plan.label} — passage ${i + 1} (${spec.variant})`;
  return `${plan.label} — passage ${i + 1}`;
}

/**
 * Assemble one section's units. `onProgress({ done, total, label })` fires
 * before each unit. Returns an array of { kind, payload, verified }.
 */
export async function assembleSection(planKey, { apiKey, signal, onProgress } = {}) {
  const plan = SECTION_PLANS[planKey];
  if (!plan) throw new Error(`Unknown section: ${planKey}`);
  const units = [];
  const total = plan.units.length;
  const base = { test: plan.test, subject: plan.subject, apiKey, signal };

  for (let i = 0; i < total; i++) {
    const spec = plan.units[i];
    onProgress?.({ done: i, total, label: unitLabel(plan, spec, i) });
    if (spec.kind === "passage") {
      const { passage, verified } = await generatePassage(base);
      units.push({ kind: "passage", payload: passage, verified });
    } else if (spec.kind === "reading") {
      const { reading, verified } = await generateReading({ ...base, variant: spec.variant });
      units.push({ kind: "reading", payload: reading, verified });
    } else if (spec.kind === "writing") {
      const { writing, verified } = await generateWriting(base);
      units.push({ kind: "writing", payload: writing, verified });
    } else {
      const { questions, verified } = await generateQuestions({ ...base, count: spec.count });
      units.push({ kind: "mcq", payload: { questions }, verified });
    }
  }
  onProgress?.({ done: total, total, label: "Finishing up" });
  return units;
}

// Total questions actually generated across a unit list.
export function countQuestions(units) {
  return units.reduce((sum, u) => sum + (u.payload.questions?.length ?? 0), 0);
}
